/**
 * Périmètre géographique : Île-de-France uniquement
 * La recherche et la carte sont restreintes à cette région.
 */

// Bornes Île-de-France (latitude, longitude)
// Sud-Ouest : Yvelines / vallée de la Seine
// Nord-Est : Seine-et-Marne / Aisne
export const ILE_DE_FRANCE_BOUNDS = [
  [48.1, 1.4], // Sud-Ouest (min lat, min lng)
  [49.2, 3.4], // Nord-Est (max lat, max lng)
] as const;

// Centre par défaut (Paris)
export const ILE_DE_FRANCE_CENTER = { lat: 48.8566, lng: 2.3522 };

// Zoom adapté pour afficher l'Île-de-France
export const ILE_DE_FRANCE_ZOOM = 9;

// Villes/départements Île-de-France (pour filtres et autocomplétion)
export const ILE_DE_FRANCE_VILLES = [
  "Paris",
  "Boulogne-Billancourt",
  "Saint-Denis",
  "Argenteuil",
  "Montreuil",
  "Nanterre",
  "Créteil",
  "Versailles",
  "Colombes",
  "Courbevoie",
  "Vitry-sur-Seine",
  "Champigny-sur-Marne",
  "Saint-Maur-des-Fossés",
  "Neuilly-sur-Seine",
  "Ivry-sur-Seine",
  "Levallois-Perret",
  "Sarcelles",
  "Cergy",
  "Évry",
  "Évry-Courcouronnes",
  "Aulnay-sous-Bois",
  "Clichy",
  "Meaux",
  "Fontenay-sous-Bois",
  "Drancy",
  "Noisy-le-Grand",
  "Antony",
  "Puteaux",
  "Épinay-sur-Seine",
  "Melun",
  "Chelles",
  "Coulommiers",
  "Fontainebleau",
  "Provins",
  "Nemours",
  "Poissy",
  "Sartrouville",
  "Mantes-la-Jolie",
  "Rambouillet",
  "Saint-Germain-en-Laye",
  "Conflans-Sainte-Honorine",
  "Les Mureaux",
  "Trappes",
  "Plaisir",
  "Montigny-le-Bretonneux",
  "Guyancourt",
  "Élancourt",
  "Maurepas",
  "Vélizy-Villacoublay",
  "Issy-les-Moulineaux",
  "Vanves",
  "Malakoff",
  "Clamart",
  "Châtenay-Malabry",
  "Sceaux",
  "Bagneux",
  "Bourg-la-Reine",
  "L'Haÿ-les-Roses",
  "Cachan",
  "Fresnes",
  "Rungis",
  "Thiais",
  "Choisy-le-Roi",
  "Villeneuve-le-Roi",
  "Ablon-sur-Seine",
  "Boissy-Saint-Léger",
  "Villeneuve-Saint-Georges",
  "Brunoy",
  "Yerres",
  "Draveil",
  "Vigneux-sur-Seine",
  "Corbeil-Essonnes",
  "Ris-Orangis",
  "Grigny",
  "Viry-Châtillon",
  "Savigny-sur-Orge",
  "Longjumeau",
  "Massy",
  "Palaiseau",
  "Orsay",
  "Les Ulis",
  "Bures-sur-Yvette",
  "Gif-sur-Yvette",
  "Saint-Cyr-l'École",
  "Bois-Colombes",
  "Asnières-sur-Seine",
  "Gennevilliers",
  "Villeneuve-la-Garenne",
  "Ermont",
  "Franconville",
  "Garges-lès-Gonesse",
  "Gonesse",
  "Goussainville",
  "Louvres",
  "Luzarches",
  "Marines",
  "Montmorency",
  "Deuil-la-Barre",
  "Enghien-les-Bains",
  "Saint-Gratien",
  "Sannois",
  "Cormeilles-en-Parisis",
  "Herblay-sur-Seine",
  "Bezons",
  "Carrières-sur-Seine",
  "Chatou",
  "Le Pecq",
  "Marly-le-Roi",
  "Bussy-Saint-Georges",
  "Champs-sur-Marne",
  "Torcy",
  "Lagny-sur-Marne",
  "Château-Thierry",
  "Soissons",
] as const;

export const REGION_LABEL = "Île-de-France";
